### ISSUE TITLE
Uncaught Error: EACCES, permission denied '/home/amebel/.cache/dconf/'

### ISSUE THREAD

**Issue by AmeBel** [prrrnd/atom-git-projects#21]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.16.0-31-generic
**Thrown From**: [git-projects](https://github.com/prrrnd/atom-git-projects) package, v1.11.1

### Stack Trace

Uncaught Error: EACCES, permission denied '/home/amebel/.cache/dconf/'

```
At fs.js:0

Error: EACCES, permission denied '/home/amebel/.cache/dconf/'
  at Error (native)
  at Object.fs.readdirSync (fs.js:766:18)
  at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:427:28)
  at /home/amebel/.atom/packages/git-projects/lib/git-projects.coffee:105:24
  at Set.forEach (native)
  at Object.module.exports.getGitProjects (/home/amebel/.atom/packages/git-projects/lib/git-projects.coffee:99:15)
  at /home/amebel/.atom/packages/git-projects/lib/git-projects.coffee:121:17
  at Set.forEach (native)
  at Object.module.exports.getGitProjects (/home/amebel/.atom/packages/git-projects/lib/git-projects.coffee:99:15)
  at /home/amebel/.atom/packages/git-projects/lib/git-projects.coffee:121:17
  at Set.forEach (native)
  at Object.module.exports.getGitProjects (/home/amebel/.atom/packages/git-projects/lib/git-projects.coffee:99:15)
  at /home/amebel/.atom/packages/git-projects/lib/views/git-projects-view.coffee:59:30

```

### Commands

```
     -2:57.0 git-projects:toggle (div.settings-view.pane-item)
  2x -2:47.8 core:backspace (atom-text-editor.editor.mini)
     -2:46.8 core:confirm (atom-text-editor.editor.mini)
  2x -1:59.8 symbols-tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:20.4 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
  2x -0:18.7 symbols-tree-view:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:05.7 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:00.7 core:confirm (atom-text-editor.editor.mini)
     -0:00.7 git-projects:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-tab-status",
      "ask-stack",
      "atom-html-preview",
      "auto-detect-indentation",
      "auto-indent",
      "autoclose-html",
      "autocomplete-css",
      "autocomplete-emojis",
      "autocomplete-html",
      "autocomplete-paths",
      "block-comment",
      "block-cursor",
      "emmet",
      "compare-files",
      "git-blame",
      "git-diff-details",
      "git-history",
      "git-log",
      "git-plus",
      "atom-bootstrap3",
      "github-issues",
      "ide-haskell",
      "irc",
      "language-haskell",
      "language-matlab",
      "language-r",
      "language-matlab-octave",
      "node-resolver",
      "recent-files",
      "save-session"
    ],
    "followSymlinks": true
  },
  "git-projects": {
    "rootPath": "~",
    "showSubRepos": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.6.0
command-logger, v0.22.0
file-icons, v1.5.2
filetype-color, v0.1.4
git-projects, v1.11.1
language-c, v0.41.0
language-cmake, v0.1.1
language-cython, v0.3.0
language-javascript, v0.63.0
language-json, v0.14.0
language-make, v0.14.0
language-scheme, v1.3.0
language-yaml, v0.22.0
linter, v0.12.0
project-manager, v1.15.5
symbols-tree-view, v0.8.3
synced-sidebar, v0.2.3
vim-mode, v0.40.0

# Dev
No dev packages
```

**Comment by prrrnd** [comment]
Thank you for reporting the issue.
I believe this will be fixed in the next release, as Git projects will check the permissions. 
Meanwhile, you should be able to ignore this path in the package settings.

**Comment by prrrnd** [comment]
@AmeBel Have you experienced this issue in v1.12.0 ?

**Comment by AmeBel** [comment]
yap

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: linux 3.16.0-33-generic
**Thrown From**: [git-projects](https://github.com/prrrnd/atom-git-projects) package, v1.12.0

### Stack Trace

Uncaught Error: EACCES, permission denied '/home/amebel/.cache/dconf'

```
At fs.js:0

Error: EACCES, permission denied '/home/amebel/.cache/dconf'
  at Error (native)
  at Object.fs.readdirSync (fs.js:766:18)
  at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:427:28)
  at /home/amebel/.atom/packages/git-projects/lib/git-projects.coffee:114:7
  at Set.forEach (native)
  at Object.module.exports.findGitRepos (/home/amebel/.atom/packages/git-projects/lib/git-projects.coffee:108:15)
  at /home/amebel/.atom/packages/git-projects/lib/git-projects.coffee:126:17
  at Set.forEach (native)
  at Object.module.exports.findGitRepos (/home/amebel/.atom/packages/git-projects/lib/git-projects.coffee:108:15)
  at /home/amebel/.atom/packages/git-projects/lib/git-projects.coffee:126:17
  at Set.forEach (native)
  at Object.module.exports.findGitRepos (/home/amebel/.atom/packages/git-projects/lib/git-projects.coffee:108:15)
  at /home/amebel/.atom/packages/git-projects/lib/views/projects-list-view.coffee:54:29

```

### Commands

```
     -0:00.8 git-projects:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "block-cursor",
      "git-blame",
      "ide-haskell",
      "irc",
      "language-haskell",
      "language-matlab",
      "language-matlab-octave",
      "term2",
      "github-issues",
      "recent-projects"
    ],
    "followSymlinks": true,
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "git-projects": {
    "rootPath": "~/",
    "showSubRepos": true
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.15.0
autocomplete-css, v0.6.0
autocomplete-emojis, v1.0.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
command-logger, v0.22.0
compare-files, v0.4.1
emmet, v2.3.4
file-icons, v1.5.2
filetype-color, v0.1.4
git-diff-details, v0.8.0
git-log, v0.3.0
git-projects, v1.12.0
git-tab-status, v1.6.0
language-c, v0.42.0
language-cmake, v0.1.1
language-cython, v0.3.0
language-docker, v1.1.3
language-javascript, v0.66.0
language-json, v0.14.0
language-make, v0.14.0
language-r, v0.1.1
language-scheme, v1.3.0
language-yaml, v0.22.0
linter, v0.12.0
project-manager, v1.15.5
recent-files, v0.3.0
save-session, vundefined
symbols-tree-view, v0.8.3
synced-sidebar, v0.2.3
tabs-to-spaces, v0.9.1
trailing-spaces, v0.2.4
vim-mode, v0.41.0

# Dev
No dev packages
```

**Comment by prrrnd** [comment]
@AmeBel Let me know if today's 1.13.0 update fixed your issue.
Otherwise, could you please post the file permissions for `/home/amebel/.cache/dconf` ?

**Comment by AmeBel** [comment]
the issue persists. The file permission
`drwx------ 1 root   root       8 Mar 14 22:02 dconf`
