### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by betlgtu** [prrrnd/atom-git-projects#3]
1. Run Powershell as Administrator.
2. Then change location to the project folder.
3. Run atom.
4. Press Ctrl+Alt+O.

 and give following error:
It's say that folder  'C:\Projects\Haskell\betcomponents\.git\hooks does' not exists, but it is really exists
**Atom Version**: 0.179.0
**System**: Windows 7
**Thrown From**: [git-projects](https://github.com/prrrnd/atom-git-projects) package, v1.7.1

### Stack Trace

Uncaught Error: ENOENT, no such file or directory 'C:\Projects\Haskell\betcomponents\.git\hooks\function () {
      var key, output, value, _i, _ref, _results;
      output = {};
      for (key = _i = 0, _ref = this.length; 0 <= _ref ? _i < _ref : _i > _ref; key = 0 <= _ref ?   _i : --_i) {
        output[this[key]] = this[key];
      }
      _results = [];
      for (key in output) {
        value = output[key];
        _results.push(value);
      }
      return _results;
    }'

```
At C:\Users\Bet\AppData\Local\atom\app-0.179.0\resources\atom\common\lib\asar.js:52

Error: ENOENT, no such file or directory 'C:\Projects\Haskell\betcomponents\.git\hooks\function () {
      var key, output, value, _i, _ref, _results;
      output = {};
      for (key = _i = 0, _ref = this.length; 0 <= _ref ? _i < _ref : _i > _ref; key = 0 <= _ref ?   _i : --_i) {
        output[this[key]] = this[key];
      }
      _results = [];
      for (key in output) {
        value = output[key];
        _results.push(value);
      }
      return _results;
    }'
  at Error (native)
  at fs.lstatSync (fs.js:797:18)
  at Object.fs.lstatSync (C:\Users\Bet\AppData\Local\atom\app-0.179.0\resources\atom\common\lib\asar.js:115:14)
  at Object.module.exports.getGitProjects (C:\Users\Bet\.atom\packages\git-projects\lib\git-projects.coffee:50:15)
  at Object.module.exports.getGitProjects (C:\Users\Bet\.atom\packages\git-projects\lib\git-projects.coffee:58:17)
  at Object.module.exports.getGitProjects (C:\Users\Bet\.atom\packages\git-projects\lib\git-projects.coffee:58:17)
  at Object.module.exports.getGitProjects (C:\Users\Bet\.atom\packages\git-projects\lib\git-projects.coffee:57:16)
  at GitProjectsView.module.exports.GitProjectsView.show (C:\Users\Bet\.atom\packages\git-projects\lib\views\git-projects-view.coffee:54:28)
  at GitProjectsView.module.exports.GitProjectsView.toggle (C:\Users\Bet\.atom\packages\git-projects\lib\views\git-projects-view.coffee:44:8)
  at atom-workspace.atom.commands.add.git-projects:toggle (C:\Users\Bet\.atom\packages\git-projects\lib\git-projects.coffee:35:43)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Bet\AppData\Local\atom\app-0.179.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\Bet\AppData\Local\atom\app-0.179.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Bet\AppData\Local\atom\app-0.179.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Bet\AppData\Local\atom\app-0.179.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Bet\AppData\Local\atom\app-0.179.0\resources\app\src\window-event-handler.js:172:20)

```

### Commands

```
     -0:11.4 git-projects:toggle (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai-dark"
    ],
    "disabledPackages": [
      "haskell-ghc-mod",
      "build-systems",
      "script-runner",
      "script"
    ]
  },
  "git-projects": {
    "rootPath": "C:\\Projects\\Haskell",
    "showSubRepos": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-glsl, v0.1.3
autocomplete-haskell, v0.2.0
autocomplete-plus, v2.1.6
build, v0.23.4
git-projects, v1.7.1
git-tab-status, v1.5.3
ide-haskell, v0.3.2
language-glsl, v1.0.1
language-haskell, v1.0.0
language-powershell, v1.0.0
linter-hlint, v0.3.1
monokai-dark, v1.0.0
runcoderun, v0.5.1

# Dev
No dev packages
```

**Comment by prrrnd** [comment]
Thank you for reporting the issue @betlgtu. Does the error still occur if you set `showSubRepos` to `false` in your config?

**Comment by betlgtu** [comment]
Yes, If I set showSubRepos to false the error still
