### ISSUE TITLE
Uncaught TypeError: this.childProcess.send is not a function

### ISSUE THREAD

**Issue by gnestor** [prrrnd/atom-git-projects#56]
[Enter steps to reproduce below:]

1.CMD+SHIFT+O

**Atom Version**: 1.5.0-dev-26163f2
**System**: Mac OS X 10.11.3
**Thrown From**: [git-projects](https://github.com/prrrnd/atom-git-projects) package, v1.17.0

### Stack Trace

Uncaught TypeError: this.childProcess.send is not a function

```
At /Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/task.js:117

TypeError: this.childProcess.send is not a function
    at Task.module.exports.Task.send (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/task.js:117:27)
    at Task.module.exports.Task.start (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/task.js:108:12)
    at Function.module.exports.Task.once (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/task.js:21:18)
    at Object.module.exports.findGitRepos (/Users/grant/.atom/packages/git-projects/lib/git-projects.coffee:115:17)
    at ProjectsListView.module.exports.ProjectsListView.refreshItems (/Users/grant/.atom/packages/git-projects/lib/views/projects-list-view.coffee:67:17)
    at Immediate._onImmediate (/Users/grant/.atom/packages/git-projects/lib/views/projects-list-view.coffee:63:22)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -3:16.6.0 git-projects:toggle (atom-text-editor.editor.is-focused)
     -3:08.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:07.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:07.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:04.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-toychest.theme-native-ui.white-cursor)
     -1:23.8.0 git-projects:toggle (div.panels-item)
 13x -1:20.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:07.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:07.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:07.1.0 git-projects:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-toychest.theme-native-ui.white-cursor)
     -1:04.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:04.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:28.7.0 git-projects:toggle (div.panels-item)
     -0:26 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:25.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "RubyMotion",
      "preview",
      "SFTP-deployment",
      "language-haml",
      "mocha-test-runner",
      "Repl",
      "api-workbench",
      ".bin",
      "autocomplete-html-entities",
      "linter-flow",
      "autocomplete-flow",
      "linter-sass-lint"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "native-ui",
      "atom-toychest"
    ]
  },
  "git-projects": {
    "rootPath": "/Users/grant/Sites",
    "sortBy": "Latest modification date"
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
atom-toychest, v0.3.0
atom-wallaby, v1.0.7
autocomplete-paths, v1.0.2
file-icons, v1.6.14
git-projects, v1.17.0
hashrocket, v0.4.8
hyperclick, v0.0.35
js-hyperclick, v1.4.1
jupyter-notebook, v0.0.9
language-babel, v2.15.2
language-ejs, v0.2.0
language-gradle, v0.0.3
language-jade, v0.6.3
language-typescript-grammars-only, v1.3.0
linter, v1.11.3
linter-eslint, v6.0.0
linter-htmlhint, v1.0.2
native-ui, v0.16.1
nuclide-url-hyperclick, v0.0.35
open-recent, v5.0.0
pigments, v0.22.1
pretty-json, v0.4.1
react, v0.14.1
term3, v0.21.0
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by gnestor** [comment]
This eventually crashes Atom...
