### ISSUE TITLE
npm ERR! Failed at the git-utils@4.1.2 install script 'node-gyp rebuild'. - Windows 10

### ISSUE THREAD

**Issue by jwesstrom** [prrrnd/atom-git-projects#62]
Get this error when I try to install.

I've tried googling for it, but to me, it seems the solutions are based on people having visual studio installed, as in the actual software, and not just the redistributables?
Is it a prerequisite to have the VC suite installed for certain atom packages?

Am I missing something very obvious?

#################################
>
Installing “git-projects@1.17.0” failed.Hide output…

> git-utils@4.1.2 install C:\Users\jwess\AppData\Local\Temp\apm-install-dir-116619-11792-kzjq6k\node_modules\git-projects\node_modules\git-utils
> node-gyp rebuild

>
C:\Users\jwess\AppData\Local\Temp\apm-install-dir-116619-11792-kzjq6k\node_modules\git-projects\node_modules\git-utils>if not defined npm_config_node_gyp (node "C:\Users\jwess\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\jwess\AppData\Local\Temp\apm-install-dir-116619-11792-kzjq6k\node_modules\git-projects\node_modules\git-utils\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\jwess\AppData\Local\Temp\apm-install-dir-116619-11792-kzjq6k\node_modules\git-projects\node_modules\git-utils\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\jwess\AppData\Local\Temp\apm-install-dir-116619-11792-kzjq6k\node_modules\git-projects\node_modules\git-utils\build\binding.sln]
>
gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\jwess\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\jwess\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\jwess\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\jwess\\.atom\\.apmrc" "install" "C:\\Users\\jwess\\AppData\\Local\\Temp\\d-116619-11792-hwpwsq\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
>
npm ERR! git-utils@4.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-utils@4.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

>

**Comment by alyyasser** [comment]
+1

**Comment by xyzzy529** [comment]
Similar problem ...
Windows 10, with fresh install of Atom, I was adding the package.
Latest version of npm and npm-gyp

Here is the error message from Atom Install page:
<pre>
> git-utils@4.1.4 install C:\Users\username\AppData\Local\Temp\apm-install-dir-117231-572-1pvq85q\node_modules\git-projects\node_modules\git-utils
> node-gyp rebuild


C:\Users\username\AppData\Local\Temp\apm-install-dir-117231-572-1pvq85q\node_modules\git-projects\node_modules\git-utils>if not defined npm_config_node_gyp (node "C:\Users\username\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\username\AppData\Local\atom\app-1.15.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\username\AppData\Local\Temp\apm-install-dir-117231-572-1pvq85q\node_modules\git-projects\node_modules\git-utils\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\username\AppData\Local\Temp\apm-install-dir-117231-572-1pvq85q\node_modules\git-projects\node_modules\git-utils\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\username\AppData\Local\Temp\apm-install-dir-117231-572-1pvq85q\node_modules\git-projects\node_modules\git-utils\build\binding.sln]
C:\Users\username\AppData\Local\Temp\apm-install-dir-117231-572-1pvq85q
`-- (empty)


gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\username\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\username\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\username\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\username\AppData\Local\Temp\apm-install-dir-117231-572-1pvq85q\node_modules\git-projects\node_modules\git-utils
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\username\AppData\Local\Temp\apm-install-dir-117231-572-1pvq85q\package.json'
npm WARN apm-install-dir-117231-572-1pvq85q No description
npm WARN apm-install-dir-117231-572-1pvq85q No repository field.
npm WARN apm-install-dir-117231-572-1pvq85q No README data
npm WARN apm-install-dir-117231-572-1pvq85q No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\username\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\username\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\username\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\username\\.atom\\.apmrc" "install" "C:\\Users\\username\\AppData\\Local\\Temp\\d-117231-572-1nbat75\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! git-utils@4.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-utils@4.1.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs git-utils
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\username\AppData\Local\Temp\apm-install-dir-117231-572-1pvq85q\npm-debug.log
npm ERR! code 1
</pre>
