### ISSUE TITLE
gyp ERR! stack Error: Python executable "C:\Python35\python.EXE" is v3.5.2, which is not supported by gyp.

### ISSUE THREAD

**Issue by Tset-Noitamotua** [prrrnd/atom-git-projects#66]
From stack trace below there is this

>You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.

How to do it? 

I tried `apm install git-projects --python "C:\Python27\python.exe` with no success. 
(Sorry, noob here!)

```
C:\_GIT_VI\TEST123
λ apm install git-projects
Installing git-projects to C:\Users\username\.atom\packages failed

> git-utils@4.1.2 install C:\Users\username\AppData\Local\Temp\apm-install-dir-11697-21180-kfz4mb\node_modules\git-projects\node_modules\git-utils
> node-gyp rebuild


C:\Users\username\AppData\Local\Temp\apm-install-dir-11697-21180-kfz4mb\node_modules\git-projects\node_modules\git-utils>if not defined npm_config_node_gyp (node "C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
C:\Users\username\AppData\Local\Temp\apm-install-dir-11697-21180-kfz4mb
`-- (empty)


gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Python35\python.EXE" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:477:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\username\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\username\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\username\AppData\Local\Temp\apm-install-dir-11697-21180-kfz4mb\node_modules\git-projects\node_modules\git-utils
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\username\AppData\Local\Temp\apm-install-dir-11697-21180-kfz4mb\package.json'
npm WARN apm-install-dir-11697-21180-kfz4mb No description
npm WARN apm-install-dir-11697-21180-kfz4mb No repository field.
npm WARN apm-install-dir-11697-21180-kfz4mb No README data
npm WARN apm-install-dir-11697-21180-kfz4mb No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\username\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\username\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\username\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\username\\.atom\\.apmrc" "install" "C:\\Users\\username\\AppData\\Local\\Temp\\d-11697-21180-nci913\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! git-utils@4.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-utils@4.1.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs git-utils
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\username\AppData\Local\Temp\apm-install-dir-11697-21180-kfz4mb\npm-debug.log
npm ERR! code 1
```

Cheers
Tset

**Comment by Horta** [comment]
Same problem here:

`nstalling “git-projects@1.17.0” failed.Hide output…

> git-utils@4.1.4 install /private/var/folders/05/_l5j4d1d0gld7ykx1fpjgy9h0000gn/T/apm-install-dir-116116-22787-1bqxjwz/node_modules/git-projects/node_modules/git-utils
> node-gyp rebuild

/private/var/folders/05/_l5j4d1d0gld7ykx1fpjgy9h0000gn/T/apm-install-dir-116116-22787-1bqxjwz
└── (empty)


gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/horta/anaconda/bin/python" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:477:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/05/_l5j4d1d0gld7ykx1fpjgy9h0000gn/T/apm-install-dir-116116-22787-1bqxjwz/node_modules/git-projects/node_modules/git-utils
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/05/_l5j4d1d0gld7ykx1fpjgy9h0000gn/T/apm-install-dir-116116-22787-1bqxjwz/package.json'
npm WARN apm-install-dir-116116-22787-1bqxjwz No description
npm WARN apm-install-dir-116116-22787-1bqxjwz No repository field.
npm WARN apm-install-dir-116116-22787-1bqxjwz No README data
npm WARN apm-install-dir-116116-22787-1bqxjwz No license field.
npm ERR! Darwin 16.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/horta/.atom/.apm/.apmrc" "--userconfig" "/Users/horta/.atom/.apmrc" "install" "/private/var/folders/05/_l5j4d1d0gld7ykx1fpjgy9h0000gn/T/d-116116-22787-1th8py2/package.tgz" "--runtime=electron" "--target=1.3.9" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! git-utils@4.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-utils@4.1.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs git-utils
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/05/_l5j4d1d0gld7ykx1fpjgy9h0000gn/T/apm-install-dir-116116-22787-1bqxjwz/npm-debug.log
npm ERR! code 1
`
