### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by blankcode** [prrrnd/atom-git-projects#74]
Installing “git-projects@1.17.0” failed.Hide output…

> git-utils@4.1.4 install C:\Users\BRIANB~1\AppData\Local\Temp\apm-install-dir-1171014-3684-2j8pww.5hcev4e7b9\node_modules\git-projects\node_modules\git-utils
> node-gyp rebuild

C:\Users\BRIANB~1\AppData\Local\Temp\apm-install-dir-1171014-3684-2j8pww.5hcev4e7b9\node_modules\git-projects\node_modules\git-utils>if not defined npm_config_node_gyp (node "C:\Users\Brian Blankenship\AppData\Local\atom\app-1.22.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Brian Blankenship\AppData\Local\atom\app-1.22.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\BRIANB~1\AppData\Local\Temp\apm-install-dir-1171014-3684-2j8pww.5hcev4e7b9\node_modules\git-projects\node_modules\git-utils\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\BRIANB~1\AppData\Local\Temp\apm-install-dir-1171014-3684-2j8pww.5hcev4e7b9\node_modules\git-projects\node_modules\git-utils\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\BRIANB~1\AppData\Local\Temp\apm-install-dir-1171014-3684-2j8pww.5hcev4e7b9\node_modules\git-projects\node_modules\git-utils\build\binding.sln]
C:\Users\BRIANB~1\AppData\Local\Temp\apm-install-dir-1171014-3684-2j8pww.5hcev4e7b9
`-- (empty)

gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Brian Blankenship\AppData\Local\atom\app-1.22.0\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\Brian Blankenship\\AppData\\Local\\atom\\app-1.22.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Brian Blankenship\\AppData\\Local\\atom\\app-1.22.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\BRIANB~1\AppData\Local\Temp\apm-install-dir-1171014-3684-2j8pww.5hcev4e7b9\node_modules\git-projects\node_modules\git-utils
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\BRIANB~1\AppData\Local\Temp\apm-install-dir-1171014-3684-2j8pww.5hcev4e7b9\package.json'
npm WARN apm-install-dir-1171014-3684-2j8pww.5hcev4e7b9 No description
npm WARN apm-install-dir-1171014-3684-2j8pww.5hcev4e7b9 No repository field.
npm WARN apm-install-dir-1171014-3684-2j8pww.5hcev4e7b9 No README data
npm WARN apm-install-dir-1171014-3684-2j8pww.5hcev4e7b9 No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\Brian Blankenship\\AppData\\Local\\atom\\app-1.22.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Brian Blankenship\\AppData\\Local\\atom\\app-1.22.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Brian Blankenship\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Brian Blankenship\\.atom\\.apmrc" "install" "C:\\Users\\BRIANB~1\\AppData\\Local\\Temp\\d-1171014-3684-lpos6r.ssr7ge3ik9\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! git-utils@4.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-utils@4.1.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs git-utils
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\BRIANB~1\AppData\Local\Temp\apm-install-dir-1171014-3684-2j8pww.5hcev4e7b9\npm-debug.log <<< does not exist.
npm ERR! code 1

**Comment by hugeme** [comment]
Hi @blankcode have solved that issue?

**Comment by blankcode** [comment]
No, I've not had any other time to work on it.
