### ISSUE TITLE
Cant install git-scipts

### ISSUE THREAD

**Issue by hugeme** [prrrnd/atom-git-projects#77]
ATOM 1.25.1
 MAC 10.12.5

After opening atom, I received an report for `script`, `git-scipts` and `hydrogen` and there are some incompatibilities since some elements have been build for earlier versions of atom. So I tryied to rebuild and then reinstall those packages.  `git-scipts`  still does not work with the following report:

     apm install git-projects
      Installing git-projects to /Users/me/.atom/packages ✗
      
      > git-utils@4.1.4 install /private/var/folders/sz/cl3xl4cn0pjd9rwpb_vw1xmd7xkcgp/T/apm-install-dir-118220-7912-ctis4h.xwbuzncdi/node_modules/git-projects/node_modules/git-utils
      > node-gyp rebuild
      
      /private/var/folders/sz/cl3xl4cn0pjd9rwpb_vw1xmd7xkcgp/T/apm-install-dir-118220-7912-ctis4h.xwbuzncdi
      └── (empty)
      
      
      npm WARN deprecated coffee-script@1.7.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
      gyp ERR! configure error
      gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.4, which is not supported by gyp.
      gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
      gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
      gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
      gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
      gyp ERR! stack     at emitTwo (events.js:106:13)
      gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
      gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
      gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
      gyp ERR! stack     at emitOne (events.js:96:13)
      gyp ERR! stack     at Socket.emit (events.js:188:7)
      gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
      gyp ERR! System Darwin 16.6.0
      gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
      gyp ERR! cwd /private/var/folders/sz/cl3xl4cn0pjd9rwpb_vw1xmd7xkcgp/T/apm-install-dir-118220-7912-ctis4h.xwbuzncdi/node_modules/git-projects/node_modules/git-utils
      gyp ERR! node -v v6.9.5
      gyp ERR! node-gyp -v v3.4.0
      gyp ERR! not ok
      npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/sz/cl3xl4cn0pjd9rwpb_vw1xmd7xkcgp/T/apm-install-dir-118220-7912-ctis4h.xwbuzncdi/package.json'
      npm WARN apm-install-dir-118220-7912-ctis4h.xwbuzncdi No description
      npm WARN apm-install-dir-118220-7912-ctis4h.xwbuzncdi No repository field.
      npm WARN apm-install-dir-118220-7912-ctis4h.xwbuzncdi No README data
      npm WARN apm-install-dir-118220-7912-ctis4h.xwbuzncdi No license field.
      npm ERR! Darwin 16.6.0
      npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/me/.atom/.apm/.apmrc" "--userconfig" "/Users/me/.atom/.apmrc" "install" "/private/var/folders/sz/cl3xl4cn0pjd9rwpb_vw1xmd7xkcgp/T/d-118220-7912-1v2pibo.18ayczncdi/package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
      npm ERR! node v6.9.5
      npm ERR! npm  v3.10.10
      npm ERR! code ELIFECYCLE
      
      npm ERR! git-utils@4.1.4 install: `node-gyp rebuild`
      npm ERR! Exit status 1
      npm ERR!
        npm ERR! Failed at the git-utils@4.1.4 install script 'node-gyp rebuild'.
      npm ERR! Make sure you have the latest version of node.js and npm installed.
      npm ERR! If you do, this is most likely a problem with the git-utils package,
      npm ERR! not with npm itself.
      npm ERR! Tell the author that this fails on your system:
        npm ERR!     node-gyp rebuild
      npm ERR! You can get information on how to open an issue for this project with:
        npm ERR!     npm bugs git-utils
      npm ERR! Or if that isn't available, you can get their info via:
      npm ERR!     npm owner ls git-utils
      npm ERR! There is likely additional logging output above.
      
      npm ERR! Please include the following file with any support request:
      npm ERR!     /private/var/folders/sz/cl3xl4cn0pjd9rwpb_vw1xmd7xkcgp/T/apm-install-dir-118220-7912-ctis4h.xwbuzncdi/npm-debug.log
      npm ERR! code 1

**Comment by mirouhml** [comment]
Atom 1.58.0
Windows 11

I have the same issue with this package, any updates?
